# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: server_tests
on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_USER: loco
          MARIADB_DATABASE: loco
          MARIADB_RANDOM_ROOT_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        volumes:
          - /var/run/mysqld/:/var/run/mysqld
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Installing mariadb connector
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb-dev
    - name: Installing python dependancies
      run: pipenv sync --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 src/Server --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 src/Server --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      env:
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#          EMAIL: ${{ secrets.EMAIL }}
#          KEY: ${{ secrets.KEY }}
#      run: |
#        pipenv run pytest
