# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "server tests"
on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_USER: runner
          MARIADB_DATABASE: loco
          MARIADB_RANDOM_ROOT_PASSWORD: true
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        volumes:
          - /var/run/mysqld/:/var/run/mysqld
    steps:
    - uses: actions/checkout@v3
    - name: test database socket
      run: |
        ls /var/run
        ls /var/run/mysqld
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Installing mariadb connector
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb-dev
    - name: Setting up python venv
      run: |
        python -m venv venv
        source venv/bin/activate      
    - name: Installing python dependancies
      run: pip install -r requirements.txt
    - name: Test with pytest
      env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
          KEY: ${{ secrets.KEY }}
      run: |
        pytest src/Server
