# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing
on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Lint with flake8
      run: |
        pipenv install --dev
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 src/Server --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 src/Server --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pipenv install --dev
#        pipenv run pytest
